fail_fast: true
repos:
  - repo: local # Use a local repository
    hooks:
      - id: lint
        name: Lint code
        description: Orange is the new black code linter
        entry: oitnb
        args: [--icons, --line-length=79, --check,  --exclude=/migrations/*]
        files: ^App/
        exclude: /migrations/*
        require_serial: true
        additional_dependencies: ['oitnb==0.2.2']
        always_run: false
        language: python
        language_version: python3

      - id: imports
        name: Sort imports
        description: Isort your imports, so you don't have to
        entry: isort
        args: [--known-local-folder=App/, --skip-glob=**/migrations/*, --lai=2, --sl, --check]
        files: ^App/
        exclude: /migrations/*
        require_serial: true
        additional_dependencies: ['isort==5.10.1']
        always_run: false
        language: python
        language_version: python3
        verbose: true

  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
      -   id: trailing-whitespace
      -   id: end-of-file-fixer
