version: '3.9'

services:
  app:
    container_name: django-app
    build:
      context: ../../
      dockerfile: ./Docker/Local/Dockerfile
    image: &app app
    restart: always
    command: python3 /Project/start.py --service Django-App
    env_file: &envfile
      - ../../Envs/local.env
    ports:
      - 8000:8000
    volumes:
      - ../../Apps:/Apps
      - ../../Project:/Project
      - ../../Requirements:/Requirements
    depends_on:
      - database

  database:
    container_name: database
    platform: linux/x86_64
    image: mysql:5.6
    restart: always
    env_file: *envfile
    volumes:
      - ~/.mdbdata/BackendTemplate:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306

  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - 6378:6379
    volumes:
      - ~/.mdbdata/BackendTemplate/redisdata:/data
    depends_on:
      - database

  celery-worker:
    container_name: celery-worker
    build:
      context: ../../
      dockerfile: ./Docker/Local/Dockerfile
    image: *app
    restart: always
    env_file: *envfile
    command: python3 /Project/start.py --service Celery-Worker
    volumes:
      - ../../Apps:/Apps
      - ../../Project:/Project
    depends_on:
      - rabbitmq

  celery-beat:
    container_name: celery-beat
    build:
      context: ../../
      dockerfile: ./Docker/Local/Dockerfile
    image: *app
    env_file: *envfile
    command: python3 /Project/start.py --service Celery-Beat
    volumes:
      - ../../Apps:/Apps
      - ../../Project:/Project
    depends_on:
      - celery-worker

  flower:
    container_name: flower
    image: zoomeranalytics/flower:0.9.2-4.0.2-2
    restart: "no"
    env_file: *envfile
    ports:
      - 5555:5555
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    env_file: *envfile
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.mdbdata/BackendTemplate/rabbitmq_data:/data
    depends_on:
      - database

  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.3
    user: root
    ports:
      - 3000:3000
    volumes:
      - ~/.mdbdata/BackendTemplate/grafana_data:/var/lib/grafana
      - ~/.mdbdata/BackendTemplate/grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
    depends_on:
      - database

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.1.0
    volumes:
      - ../../Project/settings/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - database

  cloudbeaver:
    container_name: cloudbeaver
    image: dbeaver/cloudbeaver
    restart: always
    volumes:
      - ~/.mdbdata/BackendTemplate/cloudbeaver:/opt/cloudbeaver/workspace
    ports:
      - 8081:8978
    depends_on:
      - database
