name: Code format checker CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Setup container
      run: |
        pip install --upgrade pip
        ls -a
        make up
        make test
