name: Code format checker CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Setup container
      working-directory: ./
      run: |
        pip install --upgrade pip
        ls
        ls -a
        pwd
        make test
