name: Deploy code on environments

on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'dev'
      - 'create-github-actions'
  pull_request:
    branches:
      - 'master'
      - 'staging'
      - 'dev'

jobs:
  Code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: 🚁 Deploy on PRE
    # - name: 🛫 Deploy on Staging
    # - name: 🚀 Deploy on Production
    - name: 🎉 Congratulations
      run: echo "Everything is okay! 🎉"
