name: Main workflow

on:
  pull_request:
    branches:
      - 'master'
      - 'staging'
      - 'dev'

jobs:
  Check-Lint:
    runs-on: ubuntu-latest
    steps:
    - name: 🔀 Checkout
      uses: actions/checkout@v3
    - name: 📥 Download black
      run: pip3 install black==22.3.0
    - name: 📝 Check lint
      run:  make check-lint-local ENV=Ci

  Check-Imports:
    runs-on: ubuntu-latest
    steps:
    - name: 🔀 Checkout
      uses: actions/checkout@v3
    - name: 📥 Download isort
      run: pip3 install isort==5.10.1
    - name: 🆎 Check imports order
      run:  make check-imports-local ENV=Ci

  Testing:
    needs: [Check-Lint, Check-Imports]
    runs-on: ubuntu-latest
    steps:
    - name: 🔀 Checkout
      uses: actions/checkout@v3
    - name: 🐳 Set up container
      run: make upd ENV=Ci
    - name: ✅ Test
      run: make non-interactive-test ENV=Ci

  Done:
    needs: [Testing]
    runs-on: ubuntu-latest
    steps:
    - name: 🎉 Congratulations
      run: echo "Everything is okay! 🎉"
