name: Main workflow

on:
  pull_request:
    branches:
      - 'master'
      - 'staging'
      - 'dev'

jobs:
  Format:
    runs-on: ubuntu-latest
    steps:
    - name: 🔀 Checkout
      uses: actions/checkout@v3
    - name: 📥 Download black
      run: pip3 install black==22.3.0
    - name: 📝 Check lint
      run:  make check-lint-local
    - name: 📥 Download isort
      run: pip3 install isort==5.10.1
    - name: 🆎 Check imports order
      run:  make check-imports-local

  Testing:
    needs: [Format]
    runs-on: ubuntu-latest
    steps:
    - name: 🔀 Checkout
      uses: actions/checkout@v3
    - name: 🐳 Set up container
      run: make upd
    - name: ⏳ Wait for the environment to get up
      run: make wait-db
    - name: ✅ Test
      run: make non-interactive-test

  Done:
    needs: [Testing]
    runs-on: ubuntu-latest
    steps:
    - name: 🎉 Congratulations
      run: echo "Everything is okay! 🎉"
