name: Main workflow

on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'dev'
      - 'create-github-actions'
  pull_request:
    branches:
      - 'master'
      - 'staging'
      - 'dev'

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 📥 Download oitnb
      run: pip3 install oitnb==0.2.2
    - name: 📝 Check lint
      run:  make check-lint-local
    - name: 📥 Download isort
      run: pip3 install isort==5.10.1
    - name: 🆎 Check imports order
      run:  make check-sort-imports-local

  Testing:
    needs: [Lint]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 🐳 Set up container
      run: make upd
    - name: ⏳ Wait for the environment to get up
      run: make wait-db
    - name: ✅ Test
      run: make test

  Docker:
    needs: [Testing]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 🖥️ Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: ⌨️ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: 🙍 Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: 🏗️ Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./Docker/Local
        push: true
        tags: user/app:latest

  Deploy:
    needs: [Docker]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    # - name: 🚁 Deploy on PRE
    # - name: 🛫 Deploy on Staging
    # - name: 🚀 Deploy on Production

  Done:
    needs: [Deploy]
    runs-on: ubuntu-latest
    steps:
    - name: 🎉 Congratulations
      run: echo "Everything is okay! 🎉"
